name: unit_tests_windows-2022

on:
  push:
    branches: 
      - "**"  
  pull_request:
    branches: 
      - "**"  
      
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore LM-Kit-Maestro.sln       
    - name: Test
      run: dotnet test tests/LM-Kit-Maestro.Tests.csproj --verbosity normal
